name: Build APK for Flet App

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install Dependencies
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython
        pip install -r requirements.txt

    # Step 4: Install Android SDK
    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip openjdk-11-jdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $HOME/.bashrc
        echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $HOME/.bashrc
        source $HOME/.bashrc
      env:
        PATH: $HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH

    # Step 5: Accept Android SDK Licenses
    - name: Accept Android SDK Licenses
      run: |
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    # Step 6: Install Buildozer
    - name: Install Buildozer
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
        pip install buildozer

    # Step 7: Initialize Buildozer
    - name: Initialize Buildozer
      run: |
        buildozer init

    # Step 8: Build APK
    - name: Build APK
      run: |
        buildozer -v android debug
        mkdir -p build-output
        cp bin/*.apk build-output/

    # Step 9: Upload APK to GitHub Artifacts
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: build-output/*.apk
