name: Build APK with Flet CLI

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Buildozer Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential python3-dev libffi-dev \
            libssl-dev git libncurses5 libncurses5-dev \
            libreadline-dev libsqlite3-dev \
            wget curl llvm libncursesw5-dev xz-utils \
            tk-dev libxml2-dev libxmlsec1-dev libbz2-dev zlib1g-dev \
            openjdk-8-jdk unzip

    - name: Install Flutter SDK
      run: |
        sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
        git clone https://github.com/flutter/flutter.git --branch stable --depth 1 /opt/flutter
        echo "export PATH=\$PATH:/opt/flutter/bin" >> ~/.bashrc
        export PATH=$PATH:/opt/flutter/bin
        flutter doctor --android-licenses
        flutter doctor

    - name: Install Flet and Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flet
        pip install -r requirements.txt

    - name: Build APK
      run: flet build apk
      env:
        PATH: ${{ runner.env.PATH }}:/opt/flutter/bin

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: build/*.apk
