name: Build APK for Flet App

on:
  push:
    branches:
      - main  #

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Install Buildozer and Dependencies
    - name: Install Buildozer
      run: |
        sudo apt update
        sudo apt install -y build-essential libssl-dev libffi-dev python3-dev
        pip install buildozer

    # Step 5: Initialize Buildozer
    - name: Initialize Buildozer
      run: |
        buildozer init

    # Step 6: Build APK
    - name: Build APK
      run: |
        buildozer -v android debug
        mkdir -p build-output
        cp bin/*.apk build-output/
    
    # Step 7: Upload APK to GitHub Artifacts
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: build-output/*.apk
